name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시가 있을 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Node.js 버전 설정

      - name: Install dependencies
        run: yarn  # 필요에 따라 종속성 설치

      - name: Build project
        run: yarn build  # 빌드 스크립트 실행 (필요에 따라 수정)

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub의 토큰을 사용
        run: |
          cd build
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add .
          git commit -m "Initial commit"
          git branch -M main

          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          git commit --amend -m "$COMMIT_MESSAGE"

          git push --force "https://${{ secrets.GH_TOKEN }}@github.com/2xxbin/2xxbin.github.io.git" main
