name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시가 있을 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Node.js 버전 설정

      - name: Install dependencies
        run: yarn  # 필요에 따라 종속성 설치

      - name: Build project
        run: yarn build  # 빌드 스크립트 실행 (필요에 따라 수정)

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub의 토큰을 사용
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd dist  # dist 폴더로 이동
          git branch -m main
          git init
          git add .

          # 이전 커밋의 메시지 가져오기
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)  # 최신 커밋 메시지 가져오기
          git commit -m "$COMMIT_MESSAGE"  # 가져온 메시지로 커밋

          git push --force "https://${GITHUB_TOKEN}@github.com/2xxbin/2xxbin.github.io.git" main  # TOKEN을 자신의 GitHub 토큰으로 변경
